### ISSUE TITLE
initiate django models

### ISSUE THREAD

**Issue by mei-li** [luminitacristinalazarescu/codeeve#4]
Our main DB entities at the beginning are:
- Users - django has a already a user model https://docs.djangoproject.com/en/1.8/ref/contrib/auth/, users can be all, learners and coaches as well
- Projects (title, description, max number of participants, url, level?)
- Model user, project relation

**Comment by mei-li** [comment]
For start we can have a many to many relation of users and projects.
https://docs.djangoproject.com/en/1.8/topics/db/examples/many_to_many/
https://docs.djangoproject.com/en/1.8/topics/db/models/#many-to-many-relationships

That means a user (learner or coach can be in many projects and one project can have many users)
https://docs.djangoproject.com/en/1.8/topics/db/models/#many-to-many-relationships

**Comment by zampeta** [comment]
We didn't do it at our last meeting?

**Comment by luminitacristinalazarescu** [comment]
@zampeta yes we did it, but we didn't merge the PR yet. After we merge it we will close this issue.

**Comment by luminitacristinalazarescu** [comment]
I just found out a trick on how to close an issue when we merge a PR.

When merging the PR, after clicking on "Merge Pull Request" (the big green button) we should write in the comments box one of these "magic words": "Fixes" , "Closes" or "Resolves" followed by the issue number and then confirm the merge.
This will merge the PR and close the issue.

This should be a good practice, since this way it will clean our list of issues and we will know which issues were connected to which PRs.

:dancer:
